name: Build and deploy main branch
on:
    push:
        branches: [main]
permissions:
    packages: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v3
            - name: Log in to the Container registry
              uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push image
              run: "./build.sh"
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v3
            - name: Add Metal server public key to known_hosts
              run: |
                mkdir ~/.ssh
                echo "${{ vars.EQX_METAL_SERVER_SSH_PUBLIC_KEY }}" > ~/.ssh/known_hosts
                chmod 600 ~/.ssh/known_hosts
            - name: Deploy image to Metal server
              env:
                DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
                EQX_METAL_SERVER_IP: ${{ vars.EQX_METAL_SERVER_IP }}
              run: "./deploy.sh"
